SomaIotWeb/config/routes.rb
Rails.application.routes.draw do
  get 'util/setting'
  get 'util/setting_send'

  get 'util/chlidren'

  get 'util/otp'

  get 'util/monitoring'

  get 'util/setting'
  
  get 'util/monitoring_ban'

  resources :wifisets
  resources :posts
  get 'login/' => 'login#index'
  get 'login/auth' => 'login#auth'
  get 'welcome/test' => 'welcome#test'
  resources :welcome

end

SomaIotWeb/app/models/post.rb
class Post < ActiveRecord::Base
end

SomaIotWeb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

SomaIotWeb/app/controllers/login_controller.rb
require 'rubygems'
require 'socket'
require 'json'
require 'csv'

class LoginController < ApplicationController

  def index

  end

  def auth
    @pass = params[:password] # 로그인으로부터 password 파라미터를 받아온다.
    passjson = {:page_name => 'login', :admin_pw => @pass} # c core server로 보낼 json을 만듬.
    client = TCPSocket.new 'localhost', 9090 # tcp socket 9090 포트로 염
    client.puts JSON.generate(passjson) # json을 서버로 보냄
    response = client.read # 서버로 보냇을때 응답을 json 형식으로 받아옴.
    strip_json = response.strip # c 에서 받아온 \n 문자열을 짜름
    my_hash = JSON.parse(strip_json) # json 형태로 파싱함
    client.close # 소켓 닫음.

    if my_hash["verify"] == 'true' # 로그인 성공시
      render 'welcome/index' # 메인 메뉴로 이동
    else # 로그인 실패시
      render 'login/auth' # 다시로그인
    end

  end

end

SomaIotWeb/app/controllers/util_controller.rb
require 'socket'
require 'json'
require 'date'

class UtilController < ApplicationController

  def setting

    passjson = {:page_name => 'request' , :request_id => 'ssid'}
    client = TCPSocket.new 'localhost', 9090
    client.puts JSON.generate(passjson)

    response = client.read
    strip_json = response.strip
    puts strip_json

    my_hash = JSON.parse(strip_json)

    @local_ssid = my_hash["local_ssid"]
    @guest_ssid = my_hash["guest_ssid"]
    @otp_enable = my_hash["otp_enable"]

    client.close

  end

  def setting_send

    @edit_admin_pass = params[:edit_admin_pass]
    @edit_local_ssid = params[:edit_local_ssid]
    @edit_local_pass = params[:edit_local_pass]
    @edit_guest_ssid = params[:edit_guest_ssid]
    @edit_guest_pass = params[:edit_guest_pass]

    make_setting_json = {:page_name => 'ssid',:admin_pw => @edit_admin_pass, :local_ssid => @edit_local_ssid,
                          :guest_ssid => @edit_guest_ssid, :local_pass => @edit_local_pass,
                         :edit_guest_pass => @edit_guest_pass}

    client = TCPSocket.new 'localhost', 9090
    client.puts JSON.generate(make_setting_json)
    response = client.read
    strip_json = response.strip
    client.close
    redirect_to welcome_path

  end

  def monitoring
    passjson = {:page_name => 'request' , :request_id => 'con_list'}
    client = TCPSocket.new 'localhost', 9090
    client.puts JSON.generate(passjson)
    response = client.read
    strip_json = response.strip
    @my_monitoring_json = JSON.parse(strip_json)
    @info_device_list = @my_monitoring_json['con_list']
    client.close
  end

  def monitoring_ban
	  @mac = params[:MAC]
	  @ban_check = params[:ban_check]
	  passjson = {:page_name => 'ban' , :mac => @mac, :ban_check => @ban_check}
	  client = TCPSocket.new 'localhost', 9090
	  client.puts JSON.generate(passjson)
	  client.close
	  redirect_to util_monitoring_path
  end


  def chlidren

  end

  def otp

  end
	

  def otp_on_off(otp_on_off)

  end

  def otp_random_easy_word(otp_random_easy)
	
  end




end

SomaIotWeb/app/controllers/welcome_controller.rb
require 'json'

class WelcomeController < ApplicationController

  def index

  end

  def test
    my_hash = {:hello => "goodbye"}
    my_hash2 = {"page_name"=>"con_list","con_list"=>[{"1"=>"true","MAC":"c8:14:79:e8:3e:15",
                                                      "IP"=>"172.24.1.113","HOST_NAME"=>"android-ebff699db65b334b",
                                                      "rx"=>"96932","tx"=>"225657","connected"=>"1478777438","disconnected"=>"0"}, {"1"=>"true","MAC"=>"c8:14:79:e8:3e:15","IP"=>"172.24.1.113","HOST_NAME"=>"android-ebff699db65b334b","rx"=>"96932","tx"=>"225657","connected"=>"1478777438","disconnected"=>"0"}]}
    @test_json = my_hash.to_json.to_s.html_safe
    @test_json2 = my_hash2.to_json.to_s.html_safe
    puts @test_json
  end


end

SomaIotWeb/app/helpers/application_helper.rb
module ApplicationHelper
end

SomaIotWeb/app/helpers/login_helper.rb
module LoginHelper
end

SomaIotWeb/app/helpers/posts_helper.rb
module PostsHelper
end

SomaIotWeb/app/helpers/util_helper.rb
module UtilHelper
end

SomaIotWeb/app/helpers/welcome_helper.rb
module WelcomeHelper
end

SomaIotWeb/app/helpers/wifisets_helper.rb
module WifisetsHelper
end

SomaIotWeb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Temp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body class="container">
<%= yield %>
</body>
</html>

SomaIotWeb/app/views/login/auth.html.erb
<h1><%= @pass %></h1>

SomaIotWeb/app/views/login/index.html.erb
<!--=== Content Part ===-->
  <!--Reg Block-->
  <div class="reg-block">
    <div class="reg-block-header">
      <h2>관 리 자 로 그 인</h2>

    </div>

    <form action = "/login/auth" >
      <div class="input-group margin-bottom-20">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <input type="text" class="form-control" placeholder="PASSWORD" name="password">
      </div>
      <hr>

      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <input class="btn-u btn-block" type="submit" value="로 그 인">
        </div>
      </div>
     </form>

    <!-- 이제 여기에 로그인 처리를 해야된다 -->
    <!-- 서버랑 통신 요망 -->

  </div>
  <!--End Reg Block-->

SomaIotWeb/app/views/util/chlidren.html.erb
<h1>Util#chlidren</h1>
<p>자녀관리 페이지 입니다</p>

SomaIotWeb/app/views/util/monitoring.html.erb
 <div class="reg-block-monitor">
    <div class="reg-block-header">
      <h2>모니터링</h2>

      <h4> OTP 사용</h4>
	    <label class="switch">
      	<input type="checkbox">
      	<div class="slider round"></div>
	    </label>

      <h4> OTP 랜덤 / 쉬운 단어 사용 </h4>
	    <label class="switch">
        <input type="checkbox">
        <div class="slider round"></div>
      </label>

    </div>


  <div class="table-responsive"></div>
    <table class="table table-bordered">

      <tr class="info">
        <th>Mac</th>
        <th>IP  </th>
        <th>기기명 </th>
        <th>RX</th>
        <th>TX</th>
        <th>들어온 시간</th>
        <th>나간 시간</th>
	      <th>마지막 접속 시간</th>
	      <th>차단하기</th>
      </tr>

      <% @info_device_list.each do |info| %>

          <% t = ((Time.now).to_i - info['connected'].to_i) %>
          <% mm, ss = t.divmod(60) %> <!-- 분과 초를 판단할 수 있다 -- >
          <% hh, mm = mm.divmod(60) %> <!-- 시과 분를 판단할 수 있다 -- >
          <% dd, hh = hh.divmod(24) %> <!-- 일과 시를 구할 수 있다 -- >

          <% flag = info['flag'] %> <!-- 위험, 새로운 유저 기존유저를 판별하는 변수 -->
          <% check = info['ban_check'] %> <!-- 차단 당햇는지 아닌지 판단하는 변수 -->

          <% if flag == '2' %> <!-- 위험한 공격을 시도하고 있는 패킷일시 -->
                  <tr class = 'bg-danger'>
                    <td> <%= info['MAC'] %></td>
                    <td> <%= info['IP'] %></td>
                    <td> <%= info['HOST_NAME'] %></td>
                    <td> <%= ((info['rx'].to_i)/1024).to_s +  'Kb' %></td>
                    <td> <%= ((info['tx'].to_i)/1024).to_s +  'Kb' %></td>
                    <td> <%= DateTime.strptime(info['connected'],'%s') %></td>
                    <td> <%= DateTime.strptime(info['disconnected'], '%s') %></td>
                    <td><%= "%d 일, %d 시, %d 분전" % [dd, hh, mm] %> </td>
                    <% if check == '1' %> <!-- 차단된 유저 일때 -->
                        <td><%= link_to '차단해체', util_monitoring_ban_path(MAC: info['MAC'], ban_check: check), :class => "btn btn-primary" %></td>
                    <% elsif check == '0' %> <!--  차단된 유저가 아닐때 -->
                        <td><%= link_to '차단하기', util_monitoring_ban_path(MAC: info['MAC'], ban_check: check), :class => "btn btn-danger" %></td>
                    <% end %>
                  </tr>
          <% elsif flag == '1' %> <!-- 새로운 유저가 접속햇을때 -->
                  <tr class = 'bg-color-green'>
                    <td> <%= info['MAC'] %></td>
                    <td> <%= info['IP'] %></td>
                    <td> <%= info['HOST_NAME'] %></td>
                    <td> <%= ((info['rx'].to_i)/1024).to_s +  'Kb' %></td>
                    <td> <%= ((info['tx'].to_i)/1024).to_s +  'Kb' %></td>
                    <td> <%= DateTime.strptime(info['connected'],'%s') %></td>
                    <td> <%= DateTime.strptime(info['disconnected'], '%s') %></td>
                    <td><%= "%d 일, %d 시, %d 분전" % [dd, hh, mm] %> </td>
                    <% if check == '1' %>
                        <td><%= link_to '차단해체', util_monitoring_ban_path(MAC: info['MAC'], ban_check: check), :class => "btn btn-primary" %></td>
                    <% elsif check == '0' %>
                        <td><%= link_to '차단하기', util_monitoring_ban_path(MAC: info['MAC'], ban_check: check), :class => "btn btn-danger" %></td>
                    <% end %>
                  </tr>
          <% else %> <!-- 기존 유저일때 -->
                  <tr class = 'bg-color-white'>
                    <td> <%= info['MAC'] %></td>
                    <td> <%= info['IP'] %></td>
                    <td> <%= info['HOST_NAME'] %></td>
                    <td> <%= ((info['rx'].to_i)/1024).to_s +  'Kb' %></td>
                    <td> <%= ((info['tx'].to_i)/1024).to_s +  'Kb' %></td>
                    <td> <%= DateTime.strptime(info['connected'],'%s') %></td>
                    <td> <%= DateTime.strptime(info['disconnected'], '%s') %></td>
                    <td><%= "%d 일, %d 시, %d 분전" % [dd, hh, mm] %> </td>
                    <% if check == '1' %>
                        <td><%= link_to '차단해체', util_monitoring_ban_path(MAC: info['MAC'], ban_check: check), :class => "btn btn-primary" %></td>
                    <% elsif check == '0' %>
                        <td><%= link_to '차단하기', util_monitoring_ban_path(MAC: info['MAC'], ban_check: check), :class => "btn btn-danger" %></td>
                    <% end %>
                  </tr>
          <% end %>
      <% end %>

    </table>
   </div>
  </div>

SomaIotWeb/app/views/util/otp.html.erb
<h1>Util#otp</h1>
<p>오티피 설정 페이지입니다</p>

SomaIotWeb/app/views/util/setting.html.erb
  <!--Reg Block-->

  <form action="/util/setting_send">

    <div class="reg-block">
      <div class="reg-block-header">
        <h2>공유기 관리자 비밀번호 변경</h2>
      </div>

      <div class="input-group margin-bottom-20">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <input type="text" class="form-control" placeholder="변경 할 관리자 비밀번호" name="edit_admin_pass">
      </div>
    </div>

    <div class="reg-block">
      <div class="reg-block-header">
        <h2>현재 공유기 이름 <br>
          (SSID) : <%= @local_ssid %> </h2>
      </div>


      <div class="input-group margin-bottom-20">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <input type="text" class="form-control" placeholder="변경할 공유기 이름(SSID)" name="edit_local_ssid">
      </div>

      <div class="input-group margin-bottom-20">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <input type="text" class="form-control" placeholder="내부 비밀번호" name="edit_local_pass">
      </div>

      <hr>

      <div class="reg-block-header">
        <h2>현재 손님용 공유기 이름 <br>
          (SSID) : <%= @guest_ssid %> </h2>
      </div>

      <div class="input-group margin-bottom-20">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <input type="text" class="form-control" placeholder="손님용 공유기 이름(SSID)" name="edit_guest_ssid">
      </div>

      <div class="input-group margin-bottom-20">
        <span class="input-group-addon"><i class="fa fa-lock"></i></span>
        <input type="text" class="form-control" placeholder="손님용 비밀번호" name="edit_guest_pass">
      </div>

      <hr>

      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <input class="btn-u btn-block" type="submit" value="변경완료">
        </div>
      </div>
    </div>

  </form>


  <!--End Reg Block-->

SomaIotWeb/app/views/util/setting_send.html.erb
<h1> 에러가없다면 보이는 페이지</h1>

SomaIotWeb/app/views/welcome/index.html.erb
<div class="welcome-wrapper" xmlns="http://www.w3.org/1999/html">

  <div class="section">
    <div class="btn-wrapper">
      <div class="btn-section">
        <%= link_to "", util_setting_path, :class => "img btn animated zoomIn" %>
      <div class="title">
        SSID 설정
      </div>
      </div>
    </div>
  </div>

  <div class="section">
    <div class="btn-wrapper">
      <div class="btn-section">
        <%= link_to "", util_monitoring_path, :class => "img2 btn animated zoomIn" %>
        <div class="title">
          모니터링 및 OTP 설정
        </div>
      </div>
    </div>
  </div>

</div>